name: Build and Push Docker Images

on:
  push:
    branches:
      - prod  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push production images
      run: |
        docker compose \
          --profile prod \
          -f docker-compose.yml \
          build
        docker compose \
          --profile prod \
          -f docker-compose.yml \
          push
      env:
        ENV_FILE: ./.env  # Peut varier selon vos besoins et secrets


