services:
  website-insash:
    build: .
    image: website-insash
    container_name: website-insash
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    networks:
      - frontend
  website-insash-api:
    build: ./backend
    image: website-insash-api
    container_name: website-insash-api
    env_file: ./backend/cmd/.env
    volumes:
      - ./backend:/var/www/app
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend
  postgres: 
    image: postgres:16
    container_name: website-insash-database
    ports:
      - "5432:5432"
    env_file: ./backend/database/.env
    volumes:
    - ./backend/database/database_mock.sql:/docker-entrypoint-initdb.d/database_mock.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge