services:
  website-insash:
    # nginx + frontend
    build: .
    image: website-insash
    container_name: website-insash
    ports:
      - "10000:80"
    networks:
      - website

  website-insash-backend:
    build: insash_website_backend
    image: website-insash-backend
    container_name: website-insash-backend
    env_file: insash_website_backend/cmd/.env
    networks:
      - website

  website-insash-database:
    image: postgres:16
    container_name: website-insash-database
    env_file: ./database/.env
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - website

networks:
  website:
    driver: bridge
