services:
  ## ---------- PRODUCTION
  # App build & servie via nginx

  insash-website-prod:
    # nginx + frontend
    build:
      context: .
      dockerfile: dockerfile.prod
    profiles:
      - prod
    image: insash-website
    container_name: insash-website
    ports:
      - "10000:80"
    networks:
      - website
    depends_on:
      - insash_website_strapi

  insash_website_strapi:
    container_name: insash_website_strapi
    profiles:
      - prod
    build:
      context: ./insash_website_strapi
      dockerfile: Dockerfile.prod
    image: insash_website_strapi:latest
    env_file: ./insash_website_strapi/env/strapi.env
    volumes:
      - ./insash_website_strapi/config:/opt/app/config
      - ./insash_website_strapi/src:/opt/app/src
      - ./insash_website_strapi/package.json:/opt/package.json
      - ./insash_website_strapi/package-lock.json:/opt/package-lock.json

      - ./insash_website_strapi/env/strapi.env:/opt/app/.env
      - ./insash_website_strapi/public/uploads:/opt/app/public/uploads

    networks:
      - website
    depends_on:
      - insash_website_strapiDB

  ## ---------- DEVELOPMENT
  # App en live server via Andular

  insash-website-dev:
    # live service for dev
    build:
      context: .
      dockerfile: dockerfile.dev
    profiles:
      - dev
    image: insash-website-dev
    container_name: insash-website-dev
    ports:
      - "4200:4200"
    volumes:
      - ./insash_website_frontend:/app
      - /app/node_modules
    networks:
      - website
    depends_on:
      - insash_website_strapi_dev

  insash_website_strapi-dev:
    container_name: insash_website_strapi_dev
    profiles:
      - dev
    build:
      context: ./insash_website_strapi
    image: insash_website_strapi_dev:latest
    env_file: ./insash_website_strapi/env/strapi.env
    volumes:
      - ./insash_website_strapi/config:/opt/app/config
      - ./insash_website_strapi/src:/opt/app/src
      - ./insash_website_strapi/package.json:/opt/package.json
      - ./insash_website_strapi/package-lock.json:/opt/package-lock.json

      - ./insash_website_strapi/env/strapi.env:/opt/app/.env
      - ./insash_website_strapi/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - website
    depends_on:
      - insash_website_strapiDB

  insash_website_strapiDB:
    container_name: insash_website_strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    env_file: ./insash_website_strapi/env/postgres.env
    image: postgres:14.5-alpine
    volumes:
      - insash_website_strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    networks:
      - website

networks:
  website:
    driver: bridge

volumes:
  insash_website_strapi-data:
