FROM golang:1.22

USER www-data

WORKDIR /var/www/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

# Remet un workdir pour spécifier la racine où seront cherché tout les fichiers
WORKDIR /var/www/app/cmd   

CMD ["go", "run", "."]
