# ---[backend build]--- #
FROM golang:1.22 AS build

WORKDIR /build
COPY ./ ./

RUN go mod download 
RUN go mod verify

WORKDIR /build/cmd   

RUN go build -o backend

# ---[serve]--- #
FROM debian
COPY --from=build /build/cmd/backend /var/www/app/backend
CMD /var/www/app/backend
